LaunchLink/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("about.urls")),
    path('accounts/', include("accounts.urls")),
    path('projects/', include("projects.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = "about"
urlpatterns = [
    path("", views.home, name="home"),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("new-client", views.new_client, name="new-client"),
    path("new-business", views.new_business, name="new-business"),
    path("new-volunteer", views.new_volunteer, name="new-volunteer"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("volunteers/<int:volunteer_id>", views.volunteer_profile, name="volunteer-profile"),
    path("clients/<int:client_id>", views.client_profile, name="client-profile"),
    path("business/<int:business_id>", views.business_profile, name="business-profile"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns = [
    path("new-project/<int:request_id>", views.new_project, name="new-project"),
    path("new-request", views.new_request, name="new-request"),
    path("new-task/<int:project_id>", views.new_task, name="new-task"),
    path("<int:project_id>", views.project_view, name="project-view"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("requests", views.requests, name="requests"),
    path("reject-request/<int:request_id>", views.reject_request, name="reject-request"),
    path("tasks", views.tasks, name="tasks"),
    path("complete-task/<int:task_id>", views.complete_task, name="complete-task"),
    path("hours", views.hours, name="hours"),
    path("no-access", views.no_access, name="no-access"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models import Sum
class User(AbstractUser):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(max_length=254)
    number = PhoneNumberField(blank=True)
    img = models.ImageField(upload_to='avatars', default='avatars/blank_profile.png')
    address = models.CharField(max_length=150)
    is_volunteer = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    def __str__(self):
        return self.username

class Volunteer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='volunteer')
    grade_level = models.IntegerField()
    # volunteer_hours = models.IntegerField(default = 0)
    # skills = models.TextField()
    # interests = models.TextField()
    # availability = models.TextField()  

    def __str__(self):
        return self.user.username
    
    def get_hours(self):
        return self.logs.aggregate(total_hours=Sum('hours')).get('total_hours') or 0
    
class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='requester')
    
    def __str__(self):
        return self.user.username
    
class Business(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='businesses') 
    name = models.CharField(max_length=150)
    description = models.TextField()
    address = models.CharField(max_length=150)
    
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Client, Business, Volunteer
from django import forms
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField

class ClientSignUpForm(UserCreationForm):
    img = forms.ImageField()
    first_name = forms.CharField(max_length=100,)
    last_name = forms.CharField(max_length=100,)
    email = forms.EmailField(max_length=150,)    
    phone_number = PhoneNumberField()
    address = forms.CharField(max_length=100, )


    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone_number', 'address', 'img', 'password1', 'password2']
        
        
    def save(self, commit=True):
        user = super(ClientSignUpForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.address = self.cleaned_data['address']
        user.number = self.cleaned_data['phone_number']
        user.img = self.cleaned_data['img']
        user.is_client = True
        
        if commit:
            user.save()
        
        requester = Client.objects.create(
            user=user,
        )
        return requester
    def __init__ (self, *args, **kwargs):
        super(ClientSignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        })
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        })
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        })
        self.fields['address'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '123 Sesame Street'
        })
        self.fields['phone_number'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '+1 123 456 7890'
        })
        self.fields['img'].widget = forms.FileInput(attrs={
            'class': 'form-control',
        })
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
        })

class VolunteerSignUpForm(UserCreationForm):
    img = forms.ImageField()
    first_name = forms.CharField(max_length=100,)
    last_name = forms.CharField(max_length=100,)
    email = forms.EmailField(max_length=150,)    
    phone_number = PhoneNumberField()
    address = forms.CharField(max_length=100, )
    grade = forms.DecimalField(max_digits=2, decimal_places=0)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'grade', 'email', 'phone_number', 'address', 'img', 'password1', 'password2']
        
        
    def save(self, commit=True):
        user = super(VolunteerSignUpForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.address = self.cleaned_data['address']
        user.number = self.cleaned_data['phone_number']
        user.img = self.cleaned_data['img']
        user.is_volunteer = True
        
        if commit:
            user.save()
        
        requester = Volunteer.objects.create(
            user=user,
            grade_level=self.cleaned_data['grade'],
        )
        return requester
    def __init__ (self, *args, **kwargs):
        super(VolunteerSignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        })
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'First Name'
        })
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Last Name'
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        })
        self.fields['address'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '123 Sesame Street'
        })
        self.fields['phone_number'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '+1 123 456 7890'
        })
        self.fields['img'].widget = forms.FileInput(attrs={
            'class': 'form-control',
        })
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control',
        })   
        self.fields['grade'].widget = forms.NumberInput(attrs={
            'class': 'form-control',
            'placeholder': '10'
        })

class BusinessSignUpForm(forms.ModelForm):
    name = forms.CharField(max_length=150)
    description = forms.CharField()
    address = forms.CharField(max_length=150)

    class Meta:
        model = Business
        fields = ['name', 'address', 'description']

    def save(self, commit=True):
        business = super(BusinessSignUpForm, self).save(commit=False)
        business.name = self.cleaned_data['name']
        business.description = self.cleaned_data['description']
        business.address = self.cleaned_data['address']
        
        if commit:
            business.save()
        return business
    
    def __init__ (self, *args, **kwargs):
        super(BusinessSignUpForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Business Name'
        })
        self.fields['address'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Business Address'
        })
        self.fields['description'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Business Description'
        })

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import ClientSignUpForm, BusinessSignUpForm, VolunteerSignUpForm
from .models import Client, Business, User, Volunteer
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
import pprint
from django.contrib.auth.decorators import login_required
from django.apps import apps
ProjectRequest = apps.get_model('projects', 'ProjectRequest')

def business_profile(request, business_id):
    if Business.objects.filter(id=business_id).exists():
        business = Business.objects.get(id=business_id)
        tmp = [ project.project.all() for project in business.requests.all()]

        projects = []
        for t in tmp:
            for p in t:
                projects.append(p)
        context = {
            'business' : business,
            'projects' : projects,
        }
        return render(request, 'accounts/business_profile.html', context)
    else:
        return redirect('about:home')
    

def client_profile(request, client_id):
    if Client.objects.filter(id=client_id).exists():
        client = Client.objects.get(id=client_id)
        context = {
            'client' : client,
            'request_rejected' : ProjectRequest.objects.filter(client=client, status=3),
            'request_accepted' : ProjectRequest.objects.filter(client=client).exclude(status=3),
        }
        return render(request, 'accounts/client_profile.html', context)
    else:
        return redirect('about:home')

def volunteer_profile(request, volunteer_id):
    if Volunteer.objects.filter(id=volunteer_id).exists():
        volunteer = Volunteer.objects.get(id=volunteer_id)
        context = {
            'volunteer' : volunteer,
            'tasks' : volunteer.tasks_assigned.all(),
        }
        return render(request, 'accounts/volunteer_profile.html', context)
    else:
        return redirect('projects:dashboard')
    


# Create your views here.
def new_client(request):
    if request.method == 'POST':
        form = ClientSignUpForm(request.POST, request.FILES)
        context = {'form':form}
        if form.is_valid():
            client = form.save()
            created = True
            login(request, client.user)
            context = {'created' : created}
            return render(request, 'accounts/new_client.html', {
                'created' : created
            })
        else:
            return render(request, 'accounts/new_client.html', context)
    else:
        form = ClientSignUpForm()
        context = {
            'form' : form,
        }
        return render(request, 'accounts/new_client.html', context)

def new_volunteer(request):
    if request.method == 'POST':
        form = VolunteerSignUpForm(request.POST, request.FILES)
        context = {'form':form}
        if form.is_valid():
            volunteer = form.save()
            created = True
            login(request, volunteer.user)
            context = {'created' : created}
            return redirect('projects:dashboard')
        else:
            return render(request, 'accounts/new_volunteer.html', context)
    else:
        form = VolunteerSignUpForm()
        context = {
            'form' : form,
        }
        return render(request, 'accounts/new_volunteer.html', context)

def new_business(request):
    if not request.user.is_authenticated:
        redirect('accounts:login')
    # Check for auth
    if request.user.is_client:
        if request.method == 'POST':
            form = BusinessSignUpForm(request.POST, request.FILES)
            # form.user = Client.objects.get(user=request.user)
            context = {'form':form}
            if form.is_valid():
                business = form.save(commit=False)
                business.user = Client.objects.get(user=request.user)
                business.save()
                created = True
                context = {'created' : created}
                return redirect('projects:dashboard')
            else:
                return render(request, 'accounts/new_business.html', context)
        else:
            form = BusinessSignUpForm()
            context = {
                'form' : form,
            }
            return render(request, 'accounts/new_business.html', {
                'form' : form
            })
    else:
        return redirect('about:home')
    
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            authenticated_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, authenticated_user)
            return redirect('about:home')
        else:
            return render(request, 'accounts/login.html', {'form':form})
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('about:home'))

accounts/templates/accounts/business_profile.html
{% extends 'about/layout.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'projects/css/card.css' %}">
  {% comment %} <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}"> {% endcomment %}
{% endblock head %}
{% block body %}
  <div class="dashboard" id="boot">
    <h1>{{ business.name }}</h1>
    <p>
      Owned by: <a href="{% url 'accounts:client-profile' business.user.user.id %}">{{ business.user.user.first_name }} {{ business.user.user.last_name }}</a>
    </p>
    <div class="container project-card">
      <div style="display: flex;">
        <div style="width: 50%;">
          <h3>Details</h3>
          <table class="table align-items-center mb-0">
            <tbody>
              <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-xs">Title:</h6>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="dropdown">
                    <h6 class="mb-0 text-xs">{{ business.name }}</h6>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-xs">Description:</h6>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="dropdown">
                    <h6 class="mb-0 text-xs">{{ business.description }}</h6>
                  </div>
                </td>
              </tr>
              <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-xs">Address:</h6>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="dropdown">
                    <h6 class="mb-0 text-xs">{{ business.address }}</h6>
                  </div>
                </td>
              </tr>
              <!--Size-->
              <tr>
                <td>
                  <div class="d-flex px-2 py-1">
                    <div class="d-flex flex-column justify-content-center">
                      <h6 class="mb-0 text-xs">Number:</h6>
                    </div>
                  </div>
                </td>
                <td>
                  <div class="dropdown">
                    <h6 class="mb-0 text-xs">{{ business.user.user.number }}</h6>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div style="flex-grow: 1;">
          <h3>Owner</h3>
          <div class="dashboard-content">
            <div class="">
              <div class="card mx-2">
                <div class="card-body d-flex justify-content-between align-items-center">
                  <img src="{{ business.user.user.img.url }}"
                       alt=""
                       style="width: 50px;
                              height: 50px;
                              border-radius: 50%">
                  <div style="flex-grow: 1">
                    <h5 class="card-title">
                      <a href="{% url 'accounts:client-profile' business.user.user.id %}">{{ business.user.user.first_name }} {{ business.user.user.last_name }}</a>
                    </h5>
                    <p class="card-text">{{ business.user.user.email }}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <br>
      </div>
      {% if projects %}
        <h2>Projects Requested</h2>
        {% for project in projects %}
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card mx-2">
              <div class="card-body">
                <div class="h4 m-0">
                  {{ project.project_request.title }}
                  {% if project.status == '1' %}
                    <p style="font-size: 18px;">
                      Status: <span class="text-right lead text-warning">Finding Volunteers</span>
                    </p>
                  {% elif project.status == '2' %}
                    <p class="text-right lead text-primary">Working</p>
                  {% elif project.status == '3' %}
                    <p class="text-right lead text-info">Final Touches</p>
                  {% else %}
                    <p class="text-right lead text-success">Completed</p>
                  {% endif %}
                </div>
                <small class="text-muted">Description: {{ project.project_request.description|truncatechars:60 }}</small>
                {% if project.project_request.business %}
                  Requested by: <a href="{% url 'accounts:business-profile' project.project_request.business.id %}">{{ project.project_request.business.name }}</a>
                {% else %}
                  <p>
                    Requested by: <a href="{% url 'accounts:client-profile' project.project_request.client.id %}">{{ project.project_request.client }}</a>
                  </p>
                {% endif %}
                <p>
                  {{ project.managers.count }} {{ project.managers.count|pluralize:"Manager,Managers" }} - {{ project.developers.count }} {{ project.developers.count|pluralize:"Developer,Developers" }}
                </p>
                <small>Completed on: {{ project.updated|date:"M d, Y" }}</small>
                <a class="btn btn-primary"
                   href="{% url 'projects:project-view' project.id %}">View Details</a>
              </div>
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/login.html
{% extends "about/layout.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}" />
{% endblock head %}
{% block js %}
{% endblock js %}
{% block nav %}
{% endblock nav %}
{% block body %}
  <div class="row" id="client-form">
    <div class="col-md-12">
      <form method="post"
            enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Log In</h1>
        {{ form.errors }}
        <fieldset>
          {{ form.as_p }}
        </fieldset>
        <button type="submit">Log In</button>
        <p class="bottom-text">Not Registered? <a href="{% url 'accounts:new-client' %}">Create an account</a></p>
      </form>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/new_business.html
{% extends "about/layout.html" %}
{% load static %}
{% block body %}
    <div class="row" id="client-form">
        <div class="col-md-12">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Business Account</h1>
                {{ form.errors }}
                <fieldset>
                    <legend>
                        <span class="number">1</span>Business Info
                    </legend>
                    {{ form }}
                </fieldset>
                <button type="submit">Create Business</button>
            </form>
        </div>
    </div>
{% endblock body %}

accounts/templates/accounts/new_client.html
{% extends "about/layout.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}">
{% endblock head %}
{% block js %}
{% endblock js %}
{% block nav %}
{% endblock nav %}
{% block body %}
  <div class="row" id="client-form">
    <div class="col-md-12">
      {% if created %}
        <h1>Welcome {{ user.first_name }}!</h1>
        <div class="form">
          <p>Would you like to add your business?</p>
          <button onclick="window.location.href='{% url 'accounts:new-business' %}'">
            Yes bring me there!
          </button>
          <button onclick="window.location.href='{% url 'projects:dashboard' %}'">
            No. Take me to the dashboard!
          </button>

        </div>
        
      {% else %}
        <form action="{% url 'accounts:new-client' %}"
              method="post"
              enctype="multipart/form-data">
          {% csrf_token %}
          <h1>Sign Up</h1>
          {{ form.errors }}
          <fieldset>
            <legend>
              <span class="number">1</span> Create Your Account
            </legend>
            <label>Username:</label>
            {{ form.username }}
            <label>Password:</label>
            {{ form.password1 }}
            <label>Password Confirmation:</label>
            {{ form.password2 }}
          </fieldset>
          <fieldset>
            <legend>
              <span class="number">2</span> Your Basic Info
            </legend>
            <label>First Name:</label>
            {{ form.first_name }}
            <label>Last Name:</label>
            {{ form.last_name }}
            <label>Email:</label>
            {{ form.email }}
            <label>Phone Number:</label>
            {{ form.phone_number }}
            <label>Address:</label>
            {{ form.address }}
            <label>Profile Picture:</label>
            {{ form.img }}
          </fieldset>
          <button type="submit">Sign Up</button>
          <p class="bottom-text">Have an account? <a href="{% url 'accounts:login' %}">Log In</a></p>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/new_volunteer.html
{% extends "about/layout.html" %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}">
{% endblock head %}
{% block js %}
{% endblock js %}
{% block nav %}
{% endblock nav %}
{% block body %}
  <div class="row" id="client-form">
    <div class="col-md-12">
    <form
            method="post"
            enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Be a Volunteer!</h1>
        {{ form.errors }}
        <fieldset>
        <legend>
            <span class="number">1</span> Create Your Account
        </legend>
        <label>Username:</label>
        {{ form.username }}
        <label>Password:</label>
        {{ form.password1 }}
        <label>Password Confirmation:</label>
        {{ form.password2 }}
        </fieldset>
        <fieldset>
        <legend>
            <span class="number">2</span> Your Basic Info
        </legend>
        <label>First Name:</label>
        {{ form.first_name }}
        <label>Last Name:</label>
        {{ form.last_name }}
        <label>Grade:</label>
        {{ form.grade }}
        <label>Email:</label>
        {{ form.email }}
        <label>Phone Number:</label>
        {{ form.phone_number }}
        <label>Address:</label>
        {{ form.address }}
        <label>Profile Picture:</label>
        {{ form.img }}
        </fieldset>
        <button type="submit">Sign Up</button>
        <p class="bottom-text">Have an account? <a href="{% url 'accounts:new-client' %}">Log In</a></p>
    </form>
    </div>
  </div>
{% endblock body %}