LaunchLink/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("about.urls")),
    path('accounts/', include("accounts.urls")),
    path('projects/', include("projects.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = "about"
urlpatterns = [
    path("", views.home, name="home"),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("new-client", views.new_client, name="new-client"),
    path("new-business", views.new_business, name="new-business"),
    path("new-volunteer", views.new_volunteer, name="new-volunteer"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("volunteers/<int:volunteer_id>", views.volunteer_profile, name="volunteer-profile"),
    path("clients/<int:client_id>", views.client_profile, name="client-profile"),
    path("business/<int:business_id>", views.business_profile, name="business-profile"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns = [
    path("new-project/<int:request_id>", views.new_project, name="new-project"),
    path("new-request", views.new_request, name="new-request"),
    path("new-task/<int:project_id>", views.new_task, name="new-task"),
    path("<int:project_id>", views.project_view, name="project-view"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("requests", views.requests, name="requests"),
    path("reject-request/<int:request_id>", views.reject_request, name="reject-request"),
    path("tasks", views.tasks, name="tasks"),
    path("complete-task/<int:task_id>", views.complete_task, name="complete-task"),
    path("hours", views.hours, name="hours"),
    path("no-access", views.no_access, name="no-access"),
]

projects/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class ProjectRequest(models.Model):
    PENDING = "1"
    VERIFIED = "2"
    REJECTED = "3"
    request_status = (
        (PENDING, 'Pending Verification'),
        (VERIFIED, 'Verified'),
        (REJECTED, 'Rejected'),
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_business = models.BooleanField(default=False)
    business = models.ForeignKey('accounts.Business', on_delete=models.CASCADE, null=True, related_name='requests', default=None, blank=True)
    client = models.ForeignKey('accounts.Client', on_delete=models.CASCADE, null=True, related_name='requests')
    slug = models.SlugField()
    status = models.CharField(max_length=100, choices=request_status, default=PENDING)
    
    def save(self, *args, **kwargs):
        self.slug = slugify("request-" + self.title)
        super(ProjectRequest, self).save(*args, **kwargs)
        self.slug = slugify(self.slug + "-" + str(self.id))
        super(ProjectRequest, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.slug
    
    
class Project(models.Model):
    FINDING_VOLUNTEERS = '1'
    WORKING = '2'
    FINAL_TOUCHES = '3'
    COMPLETED = '4'
    
    project_status = (
        (FINDING_VOLUNTEERS, 'Finding Volunteers'),
        (WORKING, 'Working'),
        (FINAL_TOUCHES, 'Final Touches'),
        (COMPLETED, 'Completed'),
    )
    
    project_request = models.ForeignKey(ProjectRequest, on_delete=models.CASCADE, null=True, related_name='project')
    status = models.CharField(max_length=100, choices=project_status, default=FINDING_VOLUNTEERS)
    managers = models.ManyToManyField('accounts.Volunteer', related_name='projects_managed')
    developers = models.ManyToManyField('accounts.Volunteer', related_name='projects_developed')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    product_link = models.URLField(null=True, blank=True)
    github_link = models.URLField(null=True, blank=True)
    slug = models.SlugField()
    
    def save(self, *args, **kwargs):
        self.slug = slugify("project-" + self.project_request.title)
        super(Project, self).save(*args, **kwargs)
        self.slug = slugify(self.slug + "-" + str(self.id))
        super(Project, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.slug

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField('accounts.Volunteer', related_name='tasks_assigned')
    task_name = models.CharField(max_length=100)
    task_description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

class VolunteerLog(models.Model):
    volunteer = models.ForeignKey('accounts.Volunteer', on_delete=models.CASCADE, related_name='logs')
    project = models.ForeignKey('projects.Project', on_delete=models.CASCADE) 
    date = models.DateField(auto_now_add=True)
    hours = models.DecimalField(max_digits=3, decimal_places=1)
    description = models.TextField()

projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from pprint import pprint
from django.contrib.auth.decorators import login_required
from .forms import ProjectRequestForm, ProjectForm, TaskForm, VolunteerLogForm
from django.apps import apps
Client = apps.get_model('accounts', 'Client')
Volunteer = apps.get_model('accounts', 'Volunteer')
from .models import ProjectRequest, Project, Task, VolunteerLog

# Create your views here.
def hours(request):
    if not request.user.is_authenticated:
        redirect('accounts:login')
    if not request.user.is_volunteer:
        return redirect('projects:no-access')
    return render(request, 'projects/hours.html', {
        'hours': Volunteer.objects.get(user=request.user).logs.all().order_by('-date')
    })

def no_access(request):
    return render(request, 'projects/no-access.html')

def complete_task(request, task_id):
    if Task.objects.filter(id=task_id).exists() and request.user.is_volunteer:
        task = Task.objects.get(id=task_id)
        task.completed = True
        task.save()
        return redirect('projects:tasks')
    else:
        return redirect('projects:no-access')

def tasks(request):
    if not request.user.is_authenticated:
        redirect('accounts:login')
    if not request.user.is_volunteer:
        return redirect('projects:no-access')
    return render(request, 'projects/tasks.html', {
        'current_tasks': Volunteer.objects.get(user=request.user).tasks_assigned.filter(completed=False),
        'completed_tasks':Volunteer.objects.get(user=request.user).tasks_assigned.filter(completed=True),
    })

def reject_request(request, request_id):
    if ProjectRequest.objects.filter(id=request_id).exists() and request.user.is_volunteer:
        project_request = ProjectRequest.objects.get(id=request_id)
        project_request.status = '3'
        project_request.save()
        return redirect('projects:requests')
    else:
        return redirect('projects:no-access')
        
def requests(request):
    return render(request, 'projects/requests.html', {
        'requests' : ProjectRequest.objects.exclude(status = '3'),
        'rejected' : ProjectRequest.objects.filter(status = '3'),
    })

def dashboard(request):
    return render(request, 'projects/project_dashboard.html', {
        'projects_in_progress' : Project.objects.exclude(status = '4'),
        'completed_projects' : Project.objects.filter(status = '4'),
    })

def project_view(request, project_id):
    if Project.objects.filter(id=project_id).exists():
        project = Project.objects.get(id=project_id)
        context = {
            'project' : project,
            'tasks' : Task.objects.filter(project=project_id),
        }
        if request.user.is_authenticated:
            if request.method == 'POST' and request.user.is_volunteer:
                pprint(request.POST)
                if 'is_task' in request.POST:
                    form = TaskForm(request.POST, **{'project_id': project_id})
                    if form.is_valid():
                        task = form.save()
                        return redirect('projects:project-view', project_id)
                    else:
                        if request.user.is_volunteer:
                            context['hour_form'] = VolunteerLogForm(**{'project_id': project_id, 'user': request.user})
                        if request.user.is_volunteer and Volunteer.objects.get(user=request.user).projects_managed.filter(id=project_id).exists():
                            context['task_form'] = TaskForm(**{'project_id': project_id})
                        return render(request, 'projects/project_view.html', context)
                else:
                    form = VolunteerLogForm(request.POST, **{'project_id': project_id, 'user': request.user})
                    if form.is_valid():
                        volunteer_log = form.save()
                        return redirect('projects:hours')
                    else:
                        if request.user.is_volunteer:
                            context['hour_form'] = VolunteerLogForm(**{'project_id': project_id, 'user': request.user})
                        if request.user.is_volunteer and Volunteer.objects.get(user=request.user).projects_managed.filter(id=project_id).exists():
                            context['task_form'] = TaskForm(**{'project_id': project_id})
                        return render(request, 'projects/project_view.html', context)
            else:
                if request.user.is_volunteer:
                    context['hour_form'] = VolunteerLogForm(**{'project_id': project_id, 'user': request.user})
                if request.user.is_volunteer and Volunteer.objects.get(user=request.user).projects_managed.filter(id=project_id).exists():
                    context['task_form'] = TaskForm(**{'project_id': project_id})
                return render(request, 'projects/project_view.html', context)
        else:
            return render(request, 'projects/project_view.html', context)
    else:
        return redirect('projects:dashboard')


def new_project(request, request_id):
    if not request.user.is_authenticated:
        redirect('accounts:login')
    if request.user.is_volunteer and ProjectRequest.objects.filter(id=request_id).exists():
        if request.method == 'POST':
            form = ProjectForm(request.POST, request.FILES, **{'request_id': request_id})
            context = {'form':form}
            if form.is_valid():
                project = form.save()
                created = True
                context = {'created' : created}
                return redirect('projects:dashboard')
            else:
                return render(request, 'projects/new_project.html', context)
        else:
            form = ProjectForm(**{'request_id': request_id})
            context = {
                'form' : form,
                'project_request' : ProjectRequest.objects.get(id=request_id),
            }
            return render(request, 'projects/new_project.html', context)
    else:
        return redirect('projects:dashboard')
    

def new_request(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    if request.user.is_client:
        if request.method == 'POST':
            form = ProjectRequestForm(request.POST, request.FILES, **{'user': request.user})
            context = {'form':form}
            if form.is_valid():
                req = form.save()
                created = True
                context = {'created' : created}
                return redirect('projects:dashboard')
            else:
                return render(request, 'projects/new_request.html', context)
        else:
            form = ProjectRequestForm(**{'user': request.user})
            context = {
                'form' : form,
            }
            return render(request, 'projects/new_request.html', context)
    else:
        return redirect('about:home')
    

def new_task(request, project_id):
    if not request.user.is_authenticated:
        redirect('accounts:login')
    pprint(Project.objects.get(id=project_id).managers)
    if Project.objects.filter(id=project_id).exists() and Project.objects.get(id=project_id).managers.filter(user = request.user).exists():
        if request.method == 'POST':
            form = TaskForm(request.POST, request.FILES, **{'project_id': project_id})
            context = {'form':form}
            if form.is_valid():
                task = form.save()
                created = True
                context = {'created' : created}
                return render(request, 'projects/new_task.html', {
                    'created' : created
                })
            else:
                return render(request, 'projects/new_task.html', context)
        else:
            form = TaskForm(**{'project_id': project_id})
            context = {
                'form' : form,
            }
            return render(request, 'projects/new_task.html', context)
    else:
        return redirect('about:home')

projects/templates/projects/new_task.html
{% extends 'about/layout.html' %}
{% load static %}
{% load bootstrap5 %}

{% block body %}
    {{ created }}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
{% endblock body %}

projects/templates/projects/project_view.html
{% extends 'about/layout.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'projects/css/card.css' %}">
    <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}">
{% endblock head %}
{% block body %}
    <div class="dashboard" id="boot">
        <div class="dashboard-content">
            <h1>{{ project.project_request.title }}</h1>
            <p>
                {% if project.project_request.business %}
                    Requested by: <a href="{% url 'accounts:business-profile' project.project_request.business.id %}">{{ project.project_request.client }}</a>
                {% else %}
                    Requested by: <a href="{% url 'accounts:client-profile' project.project_request.client.id %}">{{ project.project_request.client }}</a>
                {% endif %}
            </p>
            <div class="container project-card">
                <div style="display: flex;">
                    <div style="width: 50%;">
                        <h3>Details</h3>
                        <table class="table align-items-center mb-0">
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">Title:</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <h6 class="mb-0 text-xs">{{ project.project_request.title }}</h6>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">Description:</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <h6 class="mb-0 text-xs">{{ project.project_request.description }}</h6>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">Status:</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <h6 class="mb-0 text-xs">{{ project.get_status_display }}</h6>
                                        </div>
                                    </td>
                                </tr>
                                <!--Size-->
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">Updated:</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <h6 class="mb-0 text-xs">{{ project.updated|date:"M d, Y" }}</h6>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="d-flex px-2 py-1">
                                            <div class="d-flex flex-column justify-content-center">
                                                <h6 class="mb-0 text-xs">Created:</h6>
                                            </div>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="dropdown">
                                            <h6 class="mb-0 text-xs">{{ project.created|date:"M d, Y" }}</h6>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div style="flex-grow: 1;">
                        <h3>Tasks</h3>
                        <ul class="list-group list-group-flush">
                            {% for task in tasks %}
                                {% if task.completed %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <div>
                                            <span>
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     viewBox="0 0 16 16"
                                                     width="16"
                                                     height="16">
                                                    <path d="M13.78 4.22a.75.75 0 0 1 0 1.06l-7.25 7.25a.75.75 0 0 1-1.06 0L2.22 9.28a.751.751 0 0 1 .018-1.042.751.751 0 0 1 1.042-.018L6 10.94l6.72-6.72a.75.75 0 0 1 1.06 0Z">
                                                    </path>
                                                </svg>
                                            </span>
                                            <strike>{{ task.task_name }}</strike>
                                        </div>
                                        <span style="text-align: right">
                                            {% for assign in task.assign.all %}
                                                <a href="{% url 'accounts:volunteer-profile' assign.id %}">{{ assign.user.username }}
                                                    {% if not forloop.last %},{% endif %}
                                                </a>
                                            {% endfor %}
                                        </span>
                                    </li>
                                {% else %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <div>
                                            <span>
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     viewBox="0 0 16 16"
                                                     width="16"
                                                     height="16">
                                                    <path d="M0 7.75A.75.75 0 0 1 .75 7h14.5a.75.75 0 0 1 0 1.5H.75A.75.75 0 0 1 0 7.75Z"></path>
                                                </svg>
                                            </span>&nbsp;
                                            {{ task.task_name }}
                                        </div>
                                        <span style="text-align: right">
                                            {% for assign in task.assign.all %}
                                                <a href="{% url 'accounts:volunteer-profile' assign.id %}">{{ assign.user.username }}
                                                    {% if not forloop.last %},{% endif %}
                                                </a>
                                            {% endfor %}
                                        </span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <br>
                <h3>Managers</h3>
                <div class="card-body">
                    <div class="row justify-content-center align-items-center">
                        {% for manager in project.managers.all %}
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="card mx-2">
                                    <div class="card-body d-flex justify-content-between align-items-center">
                                        <img src="{{ manager.user.img.url }}"
                                             alt=""
                                             style="width: 50px;
                                                    height: 50px;
                                                    border-radius: 50%">
                                        <div style="flex-grow: 1">
                                            <h5 class="card-title">
                                                <a href="{% url 'accounts:volunteer-profile' manager.id %}">{{ manager.user.first_name }} {{ manager.user.last_name }}</a>
                                            </h5>
                                            <p class="card-text">{{ manager.user.email }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <h3>Developers</h3>
                <div class="card-body">
                    <div class="row justify-content-center align-items-center">
                        {% for developer in project.developers.all %}
                            <div class="col-12 col-md-6 col-lg-4">
                                <div class="card mx-2">
                                    <div class="card-body d-flex justify-content-between align-items-center">
                                        <img src="{{ developer.user.img.url }}"
                                             alt=""
                                             style="width: 50px;
                                                    height: 50px;
                                                    border-radius: 50%">
                                        <div style="flex-grow: 1">
                                            <h5 class="card-title">
                                                <a href="{% url 'accounts:volunteer-profile' developer.id %}">{{ developer.user.first_name }} {{ developer.user.last_name }}</a>
                                            </h5>
                                            <p class="card-text">{{ developer.user.email }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% if task_form %}
                    <hr>
                    <br>
                    <h3>Assign Tasks:</h3>
                    <div class="style-form">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset>
                                {{task_form.is_task}}
                                <label>Assign Task:</label>
                                {{ task_form.assign }}
                                <label>Task Name:</label>
                                {{ task_form.task_name }}
                                <label>Task Description:</label>
                                {{ task_form.task_description }}
                            </fieldset>
                            <button class="form-button" type="submit">Assign</button>
                        </form>
                    </div>
                {% endif %}
                {% if hour_form %}
                    <hr>
                    <br>
                    <h3>Log Volunteer Hours:</h3>
                    <div class="style-form">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset>
                                {{ hour_form.as_p }}
                                <button class="form-button" type="submit">Log</button>
                            </fieldset>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock body %}

projects/templates/projects/requests.html
{% extends 'about/layout.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'projects/css/card.css' %}">
{% endblock head %}

{% block body %}
  <div class="dashboard">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <strong>{{ requests.count }} Active Requests</strong>
        </div>
        <div class="card-body">
          <div class="row">
            {% for request in requests %}
              <div class="col-12 col-md-6 col-lg-4">
                <div class="card mx-2">
                  <div class="card-body">
                    <div class="h4 m-0">
                      {{ request.title }}
                      {% if request.status == '1' %}
                        <p class="text-right lead text-warning">Pending Verification</p>
                      {% elif request.status == '2' %}
                        <p class="text-right lead text-success">Verified</p>
                      {% elif request.status == '3' %}
                        <p class="text-right lead text-danger">Rejected</p>
                      {% endif %}
                    </div>
                    <small class="text-muted">Description: {{ request.description|truncatechars:60 }}</small>
                    {% if request.business %}
                      <p>Requested by: <a href="{% url 'accounts:business-profile' request.business.id %}">{{ request.business.name }}</a></p>
                    {% else %}
                      <p>
                        Requested by: <a href="{% url 'accounts:client-profile' request.client.id %}">{{ request.client }}</a>
                      </p>
                    {% endif %}
                    <small>{{ request.updated|date:"M d, Y" }}</small>
                    {% if request.status == '1' %}
                      {% if user.is_volunteer %}
                      <div>
                        <a class="btn btn-danger" href="{% url 'projects:reject-request' request.id %}">Reject</a>
                      </div>
                      {% endif %}
                    {% else %}
                      <a class="btn btn-primary"
                        href="{% url 'projects:project-view' request.id %}">View Details</a>
                    {% endif %}
                    
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <br>
        </div>
      </div>
    </div>
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <strong>{{ rejected.count }} Rejected Requests</strong>
        </div>
        <div class="card-body">
          <div class="row">
            {% for request in rejected %}
              <div class="col-12 col-md-6 col-lg-4">
                <div class="card mx-2">
                  <div class="card-body rejected">
                    <div class="h4 m-0">
                      {{ request.title }}
                      {% if request.status == '1' %}
                        <p class="text-right lead text-warning">Pending Verification</p>
                      {% elif request.status == '2' %}
                        <p class="text-right lead text-success">Verified</p>
                      {% elif request.status == '3' %}
                        <p class="text-right lead text-danger">Rejected</p>
                      {% endif %}
                    </div>
                    <small class="text-muted">Description: {{ request.description|truncatechars:60 }}</small>
                    {% if request.business %}
                      <p>Requested by: <a href="{% url 'accounts:business-profile' request.business.id %}">{{ request.business.name }}</a></p>
                    {% else %}
                      <p>
                        Requested by: <a href="{% url 'accounts:client-profile' request.client.id %}">{{ request.client }}</a>
                      </p>
                    {% endif %}
                    <small>{{ request.updated|date:"M d, Y" }}</small>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}