LaunchLink/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("about.urls")),
    path('accounts/', include("accounts.urls")),
    path('projects/', include("projects.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views

app_name = "about"
urlpatterns = [
    path("", views.home, name="home"),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("new-client", views.new_client, name="new-client"),
    path("new-business", views.new_business, name="new-business"),
    path("new-volunteer", views.new_volunteer, name="new-volunteer"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("volunteers/<int:volunteer_id>", views.volunteer_profile, name="volunteer-profile"),
    path("clients/<int:client_id>", views.client_profile, name="client-profile"),
    path("business/<int:business_id>", views.business_profile, name="business-profile"),
]

projects/urls.py
from django.urls import path
from . import views

app_name = "projects"
urlpatterns = [
    path("new-project/<int:request_id>", views.new_project, name="new-project"),
    path("new-request", views.new_request, name="new-request"),
    path("new-task/<int:project_id>", views.new_task, name="new-task"),
    path("<int:project_id>", views.project_view, name="project-view"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("requests", views.requests, name="requests"),
    path("reject-request/<int:request_id>", views.reject_request, name="reject-request"),
    path("tasks", views.tasks, name="tasks"),
    path("complete-task/<int:task_id>", views.complete_task, name="complete-task"),
    path("hours", views.hours, name="hours"),
    path("no-access", views.no_access, name="no-access"),
]

about/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.
def home(request):
    return render(request, "about/home.html")

about/templates/about/home.html
{% extends "about/layout.html" %}
{% load static %}
{% load bootstrap5 %}

{% block head %}
  <link rel="stylesheet" href="{% static 'about/css/home.css' %}">
{% endblock head %}

{% block space %}
{% endblock space %}
{% block body %}

<!--Navbar-->
{% comment %} <header>  
  <nav class="navbar" style="border-bottom: 3px solid black; height: 100px; padding-top: 10px;">
    <!-- Logo + Name-->
    <div class="logo">LaunchLink</div>
    <ul class="nav-links">
      <div class="menu">
        <li><a href="{% url 'about:home' %}">Home</a></li>
        <li><a href="{% url 'about:home' %}">Dashboard</a></li>
        <li><a href="{% url 'about:home' %}">Contact</a></li>
        <li><a href="{% url 'about:home' %}">Sign In</a></li>
      </div>
    </ul>
  </nav>
</header>

<!--Section Divier-->
<hr> {% endcomment %}
<!--Welcome Section-->
<div id="intro-container">
  <img src="{% static 'about/images/boat.jpg' %}" alt="Welcome Image" style="width:100%; height: 100vh;">
  <div id="intro-centered" style="padding-top: 50px; width: max-content;"> 
    <p class="intro">
      {% if user.is_authenticated %}
        Hi,&nbsp;<span class="special-text">{{ user.first_name|capfirst }}</span>!
      {% else %}
        Hi!
      {% endif %}
      <br>Welcome to 
      <span class="special-text auto-type"></span>
      <hr style="border: 2px solid black;">
    </p>
    {% if user.is_authenticated %}
      {% if user.is_volunteer %}
        <div class="double-buttons">
          <div class="btn" onclick="window.location.href='{% url 'projects:requests' %}'"><p>View Project Requests</p></div>
          <div class="btn" onclick="window.location.href='{% url 'projects:dashboard' %}'"><p>View Open Projects</p></div>
        </div>
      {% else %}
        <div class="double-buttons">
          <div class="btn" onclick="window.location.href='{% url 'projects:new-request' %}'"><p>Request a Project!</p></div>
          <div class="btn" onclick="window.location.href='{% url 'accounts:new-business' %}'"><p>Create your Business</p></div>
        </div>
      {% endif %}
     
    {% else %}
      <div class="double-buttons">
        <div class="btn" onclick="window.location.href='{% url 'accounts:new-volunteer' %}'"><p>Be a Volunteer</p></div>
        <div class="btn" onclick="window.location.href='{% url 'projects:new-request' %}'"><p>Request a Project!</p></div>
      </div>
    {% endif %}
    
  </div>
</div> 

<!--Typing CDN + Scripts-->
<script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
<script>
    var typed = new Typed(".auto-type", {
        strings: ["LaunchLink.", "LaunchLink."],
        typeSpeed: 150,
        backSpeed: 150,
        loop: true
    })
</script>

<!--About Us-->
<br><br><br><br><br><br>
<div class="container px-4 text-center" style="flex-wrap: wrap;">
  <div class="row gx-5">
    <div class="col">
      <img src="{% static 'about/images/about-us-transparent.png' %}" alt="About Us Image" class="img-fluid">
    </div>
    <div class="col">
      <div class="p-3" style="text-align: left;">
        <h3><b>What is LaunchLink?</b></h3>
        <p style="font-size: 1.3vw; color: darkgray;">
          We are LaunchLink, a non-profit organization dedicated to empowering high school students and small businesses in our community through technology. At LaunchLink, we believe in the transformative power of technology and the potential it holds for inclusive growth. Together, we are shaping a brighter future for our community, one empowered small business at a time.
        </p>
      </div>
    </div>
  </div>
</div>
<br><br><br>

<!--How it works-->
<div style="width: 100%; background-color: #F0FFFF;">
  <br><br><br>
  <div class="container px-4 text-center">
    <div class="row gx-5">
      <div class="col">
        <div class="p-3" style="text-align: left;">
          <h3><b>How Does it Work?</b></h3>
          <p style="font-size: 1.3vw; color: darkgray;"> Our passionate team of students collaborates with local small businesses to create personalized websites to help them establish a strong online presence and reach a wider audience.</p>
        </div>
      </div>
      <div class="col">
        <img src="{% static 'about/images/target.png' %}" alt="Our Mission Image" class="img-fluid" style="width: 50%;">
      </div>
    </div>
  </div>
  <br><br><br>
</div>

<!--Joining Info-->
<br><br><br>
<div class="container px-4 text-center" style="flex-wrap: wrap;">
  <div class="row gx-5">
    <div class="col">
      <img src="{% static 'about/images/join.jpg' %}" alt="About Us Image" class="img-fluid">
    </div>
    <div class="col">
      <div class="p-3" style="text-align: left;">
        <h3><b>How Can I Join?</b></h3>
        <p style="font-size: 1.3vw; color: darkgray;">
          To begin, <a href="{% url 'accounts:new-client' %}">signup</a> and answer a few short questions. Once you have created your account, it will
          be verified by our team within 5 business days. Once your account has been verified, businesses may request for the creation or projects and
          students may sign up for a project they would like to work on.
        </p>
      </div>
    </div>
  </div>
</div>
<br><br>

{% endblock %}

about/templates/about/index.html
{% extends "about/layout.html" %}
{% load static %}
{% load bootstrap5 %}

{% block body %}

<!--Navbar-->
<nav class="navbar">
  <!-- Logo + Name-->
  <div class="logo">LaunchLink</div>
  <ul class="nav-links">
    <div class="menu">
      <li><a href="{% url 'about:index' %}">Home</a></li>
      <li><a href="{% url 'about:index' %}">About</a></li>
      <li><a href="{% url 'about:index' %}">Services</a></li>
      <li><a href="{% url 'about:index' %}">Contact</a></li>
    </div>
  </ul>
</nav>

<!--Section Divier-->
<hr>

<!--Welcome Section-->
<div id="welcome-image">
  <img src="{% static 'about/student.jpg' %}" alt="Image of Student">
</div>

{% endblock %}

about/templates/about/layout.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% block title %}
            <title>LaunchLink</title>
        {% endblock title %}
        <link rel="shortcut icon" type="image/png" href="{% static 'images/launchlink-logo.png' %}" >
        <link rel="icon"
              href="{% static 'about/images/launchlink-logo.png' %}"
              type="image/x-icon">
        <!--Bootstrap CDN--> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>
        {% block layout_css %}
            <link rel="stylesheet" href="{% static 'about/css/layout.css' %}">
            <link rel="stylesheet" href="{% static 'about/css/home.css' %}">
            <link rel="stylesheet" href="{% static 'about/css/theme.css' %}">
            <link rel="stylesheet" href="{% static 'accounts/css/form.css' %}">
            <link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
        {% endblock layout_css %}
        {% block head %}
        {% endblock head %}
    </head>
    <body style="font-family: 'Poppins', sans-serif;">
        {% block nav %}
            <nav class="navbar fixed-top"
                 style="border-bottom: 3px solid black;
                        height: 100px;
                        padding-top: 10px">
                <!-- Logo + Name-->
                <div class="logo" style="font-weight: 600;">LaunchLink</div>
                <button class="hamburger" id="hamburger">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </button>
                <ul class="nav-links dropdown-content" id="nav-links">
                    <div class="menu" style="margin-top: 10px;">
                        <li>
                            <a href="{% url 'about:home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'projects:dashboard' %}">Dashboard</a>
                        </li>
                        {% if request.user.is_client %}
                            <li>
                                <a href="{% url 'projects:new-request' %}">Create Project</a>
                            </li>
                            <li>
                                <a href="{% url 'accounts:new-business' %}">Create Business</a>
                            </li>
                        {% elif request.user.is_volunteer %}
                            <li>
                                <a href="{% url 'projects:tasks' %}">My Tasks</a>
                            </li>
                            <li>
                                <a href="{% url 'projects:hours' %}">My Hours</a>
                            </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'projects:requests' %}">Pending Requests</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url 'accounts:logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="{% url 'accounts:login' %}">Log In</a>
                            </li>
                        {% endif %}
                    </div>
                </ul>
            </nav>
        {% endblock nav %}
        {% block space %}
            <div style="height: 130px;"></div>
        {% endblock space %}
        {% block body %}{% endblock %}
        <!-- Footer -->
        <footer class="text-center text-lg-start bg-white text-muted">
            <div class="text-center p-4"
                 style="background-color: rgba(0, 0, 0, 0.025)">
                © Copyright 2023 | Designed by: <b>Jayden L, Johvanson Z, Mahasvin S.</b>
                <br>
                <!--Maybe we add the copyright liscense?-->
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery.easing@1.4.1/jquery.easing.min.js"></script>
        <script>
            const hamburger = document.querySelector('.hamburger');
            const navLinks = document.querySelector('.nav-links');

            hamburger.addEventListener('click', () => {
                navLinks.classList.toggle('show');
            });
        </script>
        {% block js %}
        {% endblock js %}
    </body>
</html>